### Resource for Meson ###
## Call via: process_sources.py "directory containing resources"
## Example: python .mesondep/process_resources.py "resources/"
## You must have bin2cpp and Quom installed. You can get them at the following links:
## https://github.com/end2endzone/bin2cpp
## https://github.com/Viatorus/quom


## Imports
from glob import glob
from pathlib import Path
import os, sys


## Main
if __name__ == '__main__':
	#Perform argument parsing
	if len(sys.argv) != 2:
		print("Usage: {} <directory containing resources>".format(sys.argv[0]))
		exit(-1)

	#Set the target extension
	TARGET_EXTENSION = "hxx.res"

	#Glob for all files in the target directory
	paths: list[Path] = glob(sys.argv[1], ["*"])

	#Loop over the list of globbed paths
	for path in paths:
		#Check if the current path is a file and it isn't a .hxx file
		if path.is_file() and not path.name.lower().endswith(TARGET_EXTENSION):
			#Announce that the current file is being processed
			print("Processing {}...".format(path.name))

			#Run bin2cpp on the file
			bin2cppPath = Path(str(Path(__file__).parent) + "/dependencies/bin2cpp.exe")
			bin2cppCommand = str(bin2cppPath) + " --file=" + str(path) + " --output=" + str(path.parent)
			os.system(bin2cppCommand)

			#Run Quom on the two files that were created
			cppPath = Path(str(path.parent) + "/" + path.stem + ".cpp")
			hPath = Path(str(path.parent) + "/" + path.stem + ".h")
			outPath = Path(str(path.parent) + "/" + path.stem + "." + TARGET_EXTENSION)
			quomCommand = "quom " + str(hPath) + " " + str(outPath)
			os.system(quomCommand)

			#Remove the source files generated by bin2cpp
			os.remove(str(cppPath))
			os.remove(str(hPath))